---
title: "Launching all test"
---

### Defining components
```{r}
working.components =  c("cloning", "dispersal", "population_grow", "extinction", "fitness_factor", "fitness_landscape", "recombination","selection_coefficient", "selection_level", "sex_determination", "density_migration_rate", "stat_sampling",
                        "macro", "random_per_replicate","initial_genotype", "coalescence", "external_file")
not.working.components = c("female_sex_allocation",  "friction", "pleiotropy")
components = c(working.components, not.working.components)
```




###Cleaning all files
```{r}
system2("rm",paste("-R ", paste(paste(components,"/", sep = ""), collapse = " ")))
system2("rm",paste("-R ", paste(paste(components,"_files","/", sep = ""), collapse = " ")))
system2("rm","output.log")
```

###function to test a component
```{r}
test <- function(component){
  res <- try(rmarkdown::render(paste(component,".Rmd", sep=""),quiet = TRUE),silent=TRUE)
  if(class(res)=="try-error"){
    cat(rep("#",50))
    cat(paste("\nSomething went wrong in the component: ",component,"\n", sep=""))
    cat(res[1])
    cat(rep("#",50), "\n \n")
  }
  else{
      cat(paste("Component: ",component," passed test \n\n", sep=""))
  }
}
```

```{r}
test("dispersal")
```


###Launching the test 
```{r}
system2("../RQuantiNemo/quantiNemo2","--version")
for(component in working.components){
  test(component)
}
```


